spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdnabialam/-configuration_properties_file.git
          clone-on-start: true
          
management:
  security:
    enabled: false
    
server:
  port: 1912